---
title: "Experimental Bleaching"
author: "S Matsuda"
date: "2022-09-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## analysis

This is an analysis of experimental bleaching trials of corals in Kaneohe Bay over the summers of 2017 and 2018. Here, I try using temperature, darkness, bright light, and menthol to bleach M. capitata and P. acuta at the larval, spat and adult stages. 

```{r cars}
library(lme4)
library(emmeans)
library(multcomp)
library(broom.mixed)
library("car") #levenes test
library("ggplot2") #plotting
library("plotrix") #plotting
require("gridExtra") #Arrange Plots for output
require("utils")
library(lubridate)
library(lmerTest)
library(RColorBrewer)
library(colorRamps)
library(cowplot)
library(tidyverse)

# Create custom ggplot theme
theme_custom <- function() {
  theme_bw(base_size = 10, base_family = "Arial") %+replace%
    theme(
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      panel.border = element_rect(color = "black", fill = NA),
      legend.background = element_rect(fill = NA, colour = NA)
    )
}
```

## temp/light 2018

```{r}




```

#survivorship
```{r}

June2018<-read.csv("June2018spawnlavasurviorship.csv")
June2018$Treatment<-as.factor(June2018$Treatment)
June2018$Conicle<-as.factor(June2018$Conicle)
June2018$Num.Larv<-as.numeric(June2018$Num.Larv)

July2018<-read.csv("July2018spawnlarvasurvivorship.csv")
July2018$Treatment<-as.factor(July2018$Treatment)
July2018$Conicle<-as.factor(July2018$Conicle)
July2018$Num.Larv<-as.numeric(July2018$Num.Larv)



#June 2018 ####

#mean
June2018_mean <- ddply(June2018, c( "Treatment", "Days"), summarise, #summarize cell counts
                 N    = length(Num.Larv[!is.na(Num.Larv)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                 mean = mean(Num.Larv, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(Num.Larv, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(Num.Larv, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
June2018_mean

plot<-ggplot(data=June2018_mean, aes(x=Days, y=mean, group = Treatment, color=Treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = F)+
  geom_point(aes(color=Treatment), size=4, show.legend = T)+
  geom_line(aes(color=Treatment), linetype=1, show.legend = F)+
  scale_color_manual(values=c("blue", "forestgreen","pink","red"))+
  xlab("") + #Label the X Axis
  #ylim(0, 11) + #set Y limits
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(colour = "black", size=1))+
        theme(aspect.ratio=1)+
  ylab("Number of larvae") +
  ggtitle("June 2018 Mortality")+
  theme(plot.title = element_text(size=20, face = "italic"));plot


#by percent lost

June2018$percent.left<-1-((1093-June2018$Num.Larv)/1093)

#mean
June2018_mean <- ddply(June2018, c( "Treatment", "Days"), summarise, #summarize cell counts
                 N    = length(percent.left[!is.na(percent.left)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                 mean = mean(percent.left, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(percent.left, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(percent.left, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
June2018_mean

June.loss.plot<-ggplot(data=June2018_mean, aes(x=Days, y=mean, group = Treatment, color=Treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = F)+
  geom_point(aes(color=Treatment), size=4, show.legend = T)+
  geom_line(aes(color=Treatment), linetype=1, show.legend = F)+
  scale_color_manual(values=c("blue", "navy","orange","magenta"))+
  xlab("") + #Label the X Axis
  #ylim(0, 11) + #set Y limits
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(colour = "black", size=1))+
        theme(aspect.ratio=1)+
  ylab("Percent alive") +
  ggtitle("June 2018 Mortality")+
  theme(plot.title = element_text(size=20, face = "italic"));June.loss.plot

#July 2018 ####

#mean
July2018_mean <- ddply(July2018, c( "Treatment", "Days"), summarise, #summarize cell counts
                 N    = length(Num.Larv[!is.na(Num.Larv)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                 mean = mean(Num.Larv, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(Num.Larv, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(Num.Larv, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
July2018_mean

plot<-ggplot(data=July2018_mean, aes(x=Days, y=mean, group = Treatment, color=Treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = F)+
  geom_point(aes(color=Treatment), size=4, show.legend = T)+
  geom_line(aes(color=Treatment), linetype=1, show.legend = F)+
  scale_color_manual(values=c("blue", "navy","orange","magenta"))+
  xlab("") + #Label the X Axis
  #ylim(0, 11) + #set Y limits
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(colour = "black", size=1))+
        theme(aspect.ratio=1)+
  ylab("Number of larvae") +
  ggtitle("July 2018 Mortality")+
  theme(plot.title = element_text(size=20, face = "italic"));plot

# plot by percent lost

July2018$percent.left<-1-((2600-July2018$Num.Larv)/2600)

#mean
July2018_mean <- ddply(July2018, c( "Treatment", "Days"), summarise, #summarize cell counts
                 N    = length(percent.left[!is.na(percent.left)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                 mean = mean(percent.left, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(percent.left, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(percent.left, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
July2018_mean

July.loss.plot<-ggplot(data=July2018_mean, aes(x=Days, y=mean, group = Treatment, color=Treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = F)+
  geom_point(aes(color=Treatment), size=4, show.legend = T)+
  geom_line(aes(color=Treatment), linetype=1, show.legend = F)+
  scale_color_manual(values=c("blue", "navy","orange","magenta"))+
  xlab("") + #Label the X Axis
  #ylim(0, 11) + #set Y limits
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(colour = "black", size=1))+
        theme(aspect.ratio=1)+
  ylab("Percent alive") +
  ggtitle("July 2018 Mortality")+
  theme(plot.title = element_text(size=20, face = "italic"));July.loss.plot
```

# plot zoox counts
```{r}

Count_D5<-read.csv("july2018 zoox counts day 19.csv")
Count_D5$Treatment<-as.factor(Count_D5$Treatment)
Count_D5$Treatment <- factor(Count_D5$Treatment, levels=c('Cool', 'Ambient', 'Warm', 'Light'))


Count_D20<-read.csv("june 2018 cell counts day 20.csv")
Count_D20$Treatment<-as.factor(Count_D20$Treatment)

Count_D20$Treatment <- factor(Count_D20$Treatment, levels=c('Ambient', 'Warm', 'Hot', 'Hotest'))

#june
june.zoox.plot<-ggplot(Count_D20, aes(x=Treatment, y=Cell.counts, fill=Treatment)) +
  geom_bar(stat="identity")+
    scale_fill_manual(values=c("blue", "navy","orange","magenta"))+
    ylim(0, 3000) + #set Y limits
  theme_minimal();june.zoox.plot



#July day 5
#mean
Count_D5_mean <- ddply(Count_D5, c( "Treatment"), summarise, #summarize cell counts
                 N    = length(Num.Zoox[!is.na(Num.Zoox)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                 mean = mean(Num.Zoox, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(Num.Zoox, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(Num.Zoox, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
Count_D5_mean

july.zoox.plot<-ggplot(Count_D5_mean, aes(x=Treatment, y=mean, fill=Treatment)) +
   geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                     width=0.1, show.legend = F)+
  scale_fill_manual(values=c("blue", "navy","orange","magenta"))+
    ylim(0, 3000) + #set Y limits
  theme_minimal();july.zoox.plot
```

Plots together
```{r}

plot_grid(June.loss.plot,june.zoox.plot, labels = c('A', 'B'), label_size = 12, align="h")


```

